# Generated by Django 4.2.4 on 2024-08-23 13:38

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_age_category_alter_product_colors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='app.category')),
            ],
        ),
        migrations.DeleteModel(
            name='BrandCategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='age_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='header',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_brand',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='app.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='Default Product Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, to='app.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=app.models.get_default_brand, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default=app.models.get_default_subcategory, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.subcategory'),
        ),
    ]
